### PR TITLE
Sprint 30 TLT-1831 Look for custom canvas membership roles

### PR DESCRIPTION
**Pull request by rascalking**
The important bits here are:
* We're adding `custom_canvas_membership_roles` to the list of LTI parameters we're pulling from the launch into the `request.LTI` dict.  
* We're bumping the version.

In order to preserve our collective sanity once this is done, I've also sorted and uniqued the list of parameters...there was at least one dupe, since it wasn't in any kind of order.  Apologies, didn't think to do that as a separate commit.

### CODE REVIEW

**Comment by bermudezjd** [comment]
Would this be a good time to look at using the  `to_params` method of the tool provider?https://github.com/tophatmonocle/ims_lti_py/blob/979244d83c2e6420d2c1941f58e52f641c56ad12/ims_lti_py/launch_params.py#L139-L156  Granted, we'd have to split out the roles keys if they are present, but it might shorten the explicit keys we'd need to define quite a bit.

**Comment by lbjay** [comment]
:+1: 

But also kinda agree about `to_params`. It's always seemed odd, the 1-by-1 extraction w/ POST.get().

**Comment by bermudezjd** [comment]
One potential advantage of using the `to_params` call is that it would make this library a little less dependent on Canvas (but more dependent on the ims_lti_py port :)  )

**Comment by lbjay** [comment]
Related: apologies for never getting around to sending you a legit pull request for converting to https://github.com/harvard-dce/dce_lti_py.

**Comment by douglashall** [comment]
@douglasjhall

**Comment by douglashall** [comment]
Looks good!

**Comment by rascalking** [comment]
The first time I looked at this code, I wanted to throw away the param copying...was just going to grab the whole POST dict, since I'd not seen `to_params` before.  We can do it, but there's a bunch of code that uses this library that assumes those keys exist in the `request.LTI` dict, and if they're not there for some reason, things will blow up.

Anyway, this is needed for a "we need to release this asap" story, but I'm certainly on board with making the change to params, then doing some substantial regression testing.

**Pull request merged**
