### PR TITLE
Use backport of OrderedDict to support python 2.6

### PR DESCRIPTION
**Pull request by arthurian**
The `collections.OrderedDict` dict subclass was introduced in python 2.7. We're using python 2.6 in our shared hosting environment, so in order to use OrderedDict, we need to use the [backported version](https://pypi.python.org/pypi/ordereddict). We modified the import to load the backported version if it's not available, although I'm not even sure if `OrderedDict` is being used (or will be used for anything).

I'm pushing this change upstream for consideration. Thoughts?

### CODE REVIEW

**Comment by rascalking** [comment]
:+1:

**Comment by douglashall** [comment]
Looks good. Can you add ordereddict to setup.py requirements?

**Comment by rascalking** [comment]
Nah...that's environment specific.

**Comment by lbjay** [comment]
:+1: but... 2.6. ouch.

**Pull request closed without merging**
